site_name: CarbonAware
site_url: https://docs.carbonaware.dev
docs_dir: docs
site_dir: site


theme:
  name: material
  palette:
    scheme: slate
    primary: green
  logo: images/logo.png
  favicon: images/favicon.png
    

nav:
  - Home: index.md
  - Scheduler:
      - Overview: scheduler/index.md
      - Python Client: scheduler/python/index.md
  - Integrations:
      - Prefect: integrations/prefect/index.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
